openapi: '3.0.5'
info:
  title: Test
  version: 0.0.1
servers:
  - url: https://test.lcl
paths:
  /events:
    get:
      operationId: getEvents
      responses:
        '200':
          description: An array of events
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Events"
components:
  schemas:
    Events:
      type: array
      items:
        type: object
        properties:
          fileName:
            type: string
            example: file.txt
          someDate:
            type: string
            format: date-time
      example:
        - fileName: fileA.txt
          someDate: 2017-07-21T17:32:28Z
        - fileName: fileB.txt
          someDate: 2020-04-20T18:11:14Z
